import { AdminProperty, AdminTestimonial, FormSubmission } from "./types";

const KEYS = {
  properties: "lonash_admin_properties",
  testimonials: "lonash_admin_testimonials",
  submissions: "lonash_admin_submissions",
};

function read<T>(key: string): T[] {
  if (typeof window === "undefined") return [];
  try {
    return JSON.parse(localStorage.getItem(key) || "[]");
  } catch {
    return [];
  }
}

function write<T>(key: string, data: T[]) {
  localStorage.setItem(key, JSON.stringify(data));
}

// ---------- Properties ----------
export function getProperties(): AdminProperty[] {
  return read<AdminProperty>(KEYS.properties);
}

export function saveProperty(p: AdminProperty) {
  const all = getProperties();
  const idx = all.findIndex((x) => x.id === p.id);
  if (idx >= 0) all[idx] = p;
  else all.unshift(p);
  write(KEYS.properties, all);
}

export function deleteProperty(id: string) {
  write(KEYS.properties, getProperties().filter((p) => p.id !== id));
}

// ---------- Testimonials ----------
export function getTestimonials(): AdminTestimonial[] {
  return read<AdminTestimonial>(KEYS.testimonials);
}

export function saveTestimonial(t: AdminTestimonial) {
  const all = getTestimonials();
  const idx = all.findIndex((x) => x.id === t.id);
  if (idx >= 0) all[idx] = t;
  else all.unshift(t);
  write(KEYS.testimonials, all);
}

export function deleteTestimonial(id: string) {
  write(KEYS.testimonials, getTestimonials().filter((t) => t.id !== id));
}

// ---------- Submissions ----------
export function getSubmissions(): FormSubmission[] {
  return read<FormSubmission>(KEYS.submissions).sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  );
}

export function addSubmission(s: FormSubmission) {
  const all = getSubmissions();
  all.unshift(s);
  write(KEYS.submissions, all);
}

export function markRead(id: string) {
  const all = getSubmissions();
  const idx = all.findIndex((s) => s.id === id);
  if (idx >= 0) all[idx].read = true;
  write(KEYS.submissions, all);
}

export function deleteSubmission(id: string) {
  write(KEYS.submissions, getSubmissions().filter((s) => s.id !== id));
}

export function unreadCount(): number {
  return getSubmissions().filter((s) => !s.read).length;
}

// ---------- Export for main site ----------
export function exportPropertiesTS(props: AdminProperty[]): string {
  return `// Generated by Lonash Admin — paste into lib/data/properties.ts
export const adminProperties = ${JSON.stringify(props, null, 2)};`;
}

export function exportTestimonialsTS(items: AdminTestimonial[]): string {
  return `// Generated by Lonash Admin — paste into lib/data/properties.ts
export const adminTestimonials = ${JSON.stringify(items, null, 2)};`;
}
